### ISSUE TITLE
Missing text - White Screen and Two errors

### ISSUE THREAD

**Issue by XinYenFon** [MissAllSunday/PrivateTopic#4]
Hai,

While i was helping one of my clients I find out some issues.
- $txt['PrivateTopics_boards_sub'] is missing
- After installing the mod profile view & admin home (only home page) giving wsod.

Error log contains those two errors:
- Can't use function return value in write context in /Sources/News.php on line 531
- Can't use function return value in write context in /Profile-View.php on line 648

**Comment by marek-veber** [comment]
We are testing this mod for PHP 5.6.19 and SMF 2.0.11 with tapatalk right now.
And there are many of bugs.

For example constructions, like:
$canSeePrivateTopics = !empty($modSettings['PrivateTopics_enable']) ? allowedTo('can_always_see_private_topics') = true;

Instead of:
$canSeePrivateTopics = !empty($modSettings['PrivateTopics_enable']) ? allowedTo('can_always_see_private_topics') : false;

Your case is probbably missing:

loadLanguage('PrivateTopics'); 

somewhere before  the error.

**Comment by MissAllSunday** [comment]
Yes, there are many silly errors like that, most of them caused by copy/pasting. Its not ready for production usage.

Just be aware that this mod only modifies SMF vanilla files, I don't remember very well but it seems tapatalk has its own set of files, this means this mod can by bypassed on tapatalk quite easily unless you manually apply this mod's changes into tapatalk's files.
